// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMXbp3rfTXZKtcQnTU4TorwVwEhtsjMnA',
    appId: '1:680822726018:web:093e006177c6bad8ab039b',
    messagingSenderId: '680822726018',
    projectId: 'my-flutter-app-13b47',
    authDomain: 'my-flutter-app-13b47.firebaseapp.com',
    storageBucket: 'my-flutter-app-13b47.firebasestorage.app',
    measurementId: 'G-R2LWZN0X55',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5kD1pSR2h9u4xqthwRatkKCyr-kOrpJA',
    appId: '1:680822726018:android:cd12c92c7d64da9cab039b',
    messagingSenderId: '680822726018',
    projectId: 'my-flutter-app-13b47',
    storageBucket: 'my-flutter-app-13b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_dkd1FVk-mcyHApuhN7bia7lXVcR4Qqw',
    appId: '1:680822726018:ios:8d2a86a6c1622e48ab039b',
    messagingSenderId: '680822726018',
    projectId: 'my-flutter-app-13b47',
    storageBucket: 'my-flutter-app-13b47.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_dkd1FVk-mcyHApuhN7bia7lXVcR4Qqw',
    appId: '1:680822726018:ios:8d2a86a6c1622e48ab039b',
    messagingSenderId: '680822726018',
    projectId: 'my-flutter-app-13b47',
    storageBucket: 'my-flutter-app-13b47.firebasestorage.app',
    iosBundleId: 'com.example.quizApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMXbp3rfTXZKtcQnTU4TorwVwEhtsjMnA',
    appId: '1:680822726018:web:994ed4580ed6a705ab039b',
    messagingSenderId: '680822726018',
    projectId: 'my-flutter-app-13b47',
    authDomain: 'my-flutter-app-13b47.firebaseapp.com',
    storageBucket: 'my-flutter-app-13b47.firebasestorage.app',
    measurementId: 'G-MCLMGDWLN0',
  );
}
